---
title: "P2_Page2_Dashboard1"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Row
-----------------------------------------------------------------------

### Vaccine Distribution in Canada

```{r, include=FALSE}
library(leaflet)
library(maps)
library(raster)
library(sp)
library(rgdal)
library(jsonlite)



on_city <- rgdal::readOGR("Ministry_of_Health_Public_Health_Unit_Boundary.geojson")

pal <- colorNumeric("viridis", NULL)

pal <- colorBin("Greens", domain = 0:100)

## Return NA instead of 0
# iszero <- function(x) {
#   for(i in 1:length(x)) {
#     if(as.numeric(gsub(',', '', x[i]))==0) {
#       x[i]=NA
#     }
#   }
#   return(x)
# }


# info <- sprintf(
#   "<strong>%s</strong><br/>Total Vaccine: %s
#   <br/>Percent of People Vaccinated: %.2f%%<br/>First doses: %s<br/>Second doses: %s<br/>Received doses administered: %.2f%%",
#   ca_data$name, format(ca_data$Total,big.mark=",",scientific=FALSE),
#   ca_data$Percent_of_population_Vaccinated, 
#   format(ca_data$First_doses,big.mark=",",scientific=FALSE), iszero(format(ca_data$Second_doses,big.mark=",",scientific=FALSE)), 
#   ca_data$Received_doses_administered
# ) %>% lapply(htmltools::HTML)

  
```

```{r}
leaflet(on_city) %>%
  addTiles()%>%  # Add defaultmap tiles
  setView(-70, 40,  zoom = 5) %>%
  # addGeoJSON(province_geo)
  addPolygons(weight = 1, stroke = TRUE, smoothFactor = 0.3, opacity = 1, fillOpacity = 0.8, 
              # fillColor = ~pal(Received_doses_administered), 
              # label = ~paste0(name, ": Total Vaccine Distributed ", formatC(Total, big.mark = ", "), 
              #                 '<br/>', 'BioNTech: ', formatC(BioNTech, big.mark = ", "), 
              #                 '<br/>', 'Moderna: ', formatC(Moderna, big.mark = ", ")),
              # label = info, 
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE))
  # addLegend(pal = pal, values = ~Received_doses_administered, opacity = 0.8)
```

Row
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

