---
title: "Page1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
```

Row
-----------------------------------------------------------------------

###  in Ontario

```{r, include=FALSE}
library(leaflet)
library(maps)
library(raster)
library(sp)
library(rgdal)
library(jsonlite)

phu <- rgdal::readOGR("./data/Ministry_of_Health_Public_Health_Unit_Boundary.geojson")
ontario.data = read.csv("./data/cases_by_status_and_phu.csv", header=T)

ontario_covid_data <- ontario.data %>%
  dplyr::filter(
    FILE_DATE == "2021-02-14"
  )
ontario_total_data <- merge(x = phu, y = ontario_covid_data, by.x='PHU_ID', by.y='PHU_NUM')
```

```{r, include=FALSE}
pal <- colorNumeric("viridis", NULL)

## Return NA instead of 0
iszero <- function(x) {
  for(i in 1:length(x)) {
    if(as.numeric(gsub(',', '', x[i]))==0) {
      x[i]=NA
    }
  }
  return(x)
}


info <- sprintf("%s<br/>%s:%s<br/>%s:%s<br/>%s:%s<br/>", ontario_total_data$PHU_NAME, 
                "Active Cases", ontario_total_data$ACTIVE_CASES,
                 "Total Death", ontario_total_data$DEATHS, 
                "Resolved Cases", ontario_total_data$RESOLVED_CASES)%>% lapply(htmltools::HTML)
```

```{r}
# ontario_total_data$ACTIVE_CASE_INTERVALS<-c( "0-50", "51-100", "101-200", "201-500", ">500")[
#                 findInterval(ontario_total_data$ACTIVE_CASES , c(0, 50, 100, 200, 500, Inf) ) ]


group <- factor((ontario_total_data$ACTIVE_CASES>50) + (ontario_total_data$ACTIVE_CASES>100)
                + (ontario_total_data$ACTIVE_CASES>200) + (ontario_total_data$ACTIVE_CASES>500), 
                labels = c("0-50", "51-100", "101-200", "201-500", ">500"))

pal <- colorFactor(c("#01579B", "#E1F5FE", "#0288D1", "#81D4FA", "#29B6F6"),
                    levels = group, ordered = TRUE)

leaflet(ontario_total_data) %>%
  addTiles()%>%
  setView(-80, 50,  zoom = 5) %>%
  addPolygons(weight = 1, stroke = TRUE,    smoothFactor = 0.3, opacity = 1, fillOpacity = 0.8,
              color = ~pal(group),
              label = info,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE)) %>%
  addLegend(pal = pal, values = ~group, opacity = 0.9)
```
Row {.tabset data-height=460}
-----------------------------------------------------------------------

### Chart B

```{r}
```

### Chart C

```{r}

```


